### PR TITLE
Fix matrix subtraction bug

### PR DESCRIPTION
**Pull request by chibi314**
I made this PR to fix the problem mentioned in #33 .

In addition, I modified the test code about subtraction.
The unit tests passes now.

### CODE REVIEW

**Comment by chibi314** [comment]
Can any maintainers merge this PR?

**Comment by dmitry1945** [comment]
Hi @chibi314 ,
It was a maintenance on our environments.
Will do this today.

Thanks.

**Comment by dmitry1945** [comment]
@chibi314 could you please update your repo with espressif:master, and rebase your PR to the latest master?
I will take your commits and then just push them to our master, then they will be pushed to the github, and PR will be closed automatically.
If I will take commits now and will rebase, then PR will be shown as open.

**Comment by chibi314** [comment]
@dmitry1945 
Thanks.
I updated my `master` and rebased `fix_matrix_subtraction` branch.
Is this OK now?

**Comment by dmitry1945** [comment]
@chibi314 yes,

will merge it with master today/tomorrow.
Thank you!

**Pull request merged**
